"""I2C register addresses for Witty Pi 5.

Register definitions from Witty Pi 5 User Manual section 13.2 (FAQ).
"""

from enum import IntEnum


class Register(IntEnum):
    """Witty Pi 5 I2C virtual register addresses."""

    # Read-only registers (0-15)
    FIRMWARE_ID = 0
    FIRMWARE_VERSION_MAJOR = 1
    FIRMWARE_VERSION_MINOR = 2
    V_USB_MSB = 3
    V_USB_LSB = 4
    V_IN_MSB = 5
    V_IN_LSB = 6
    V_OUT_MSB = 7
    V_OUT_LSB = 8
    I_OUT_MSB = 9
    I_OUT_LSB = 10
    POWER_MODE = 11
    MISSED_HEARTBEATS = 12
    RASPBERRY_PI_STATE = 13
    ACTION_REASON = 14
    MISC_STATE = 15

    # Configuration registers (16-63)
    I2C_SLAVE_ADDRESS = 16
    POWER_ON_DELAY = 17
    SHUTDOWN_DELAY = 18
    PULSE_INTERVAL = 19
    LED_ON_TIME = 20
    DUMMY_LOAD_TIME = 21
    LOW_VOLTAGE_THRESHOLD = 22
    RECOVERY_VOLTAGE_THRESHOLD = 23
    POWER_SOURCE_PRIORITY = 24
    V_USB_ADJUSTMENT = 25
    V_IN_ADJUSTMENT = 26
    V_OUT_ADJUSTMENT = 27
    I_OUT_ADJUSTMENT = 28
    WATCHDOG_HEARTBEAT_LIMIT = 29
    LOG_TO_FILE_ENABLED = 30
    FACTORY_RESET_ENABLED = 31
    STARTUP_ALARM_SECOND = 32
    STARTUP_ALARM_MINUTE = 33
    STARTUP_ALARM_HOUR = 34
    STARTUP_ALARM_DAY = 35
    SHUTDOWN_ALARM_SECOND = 36
    SHUTDOWN_ALARM_MINUTE = 37
    SHUTDOWN_ALARM_HOUR = 38
    SHUTDOWN_ALARM_DAY = 39
    BELOW_TEMP_ACTION = 40
    BELOW_TEMP_THRESHOLD = 41
    OVER_TEMP_ACTION = 42
    OVER_TEMP_THRESHOLD = 43
    DST_MODE_AND_OFFSET = 44
    DST_BEGIN_MONTH = 45
    DST_BEGIN_DAY_OR_WEEK = 46
    DST_BEGIN_HOUR = 47
    DST_BEGIN_MINUTE = 48
    DST_END_MONTH = 49
    DST_END_DAY_OR_WEEK = 50
    DST_END_HOUR = 51
    DST_END_MINUTE = 52
    DST_APPLIED = 53
    SYSTEM_CLOCK_MHZ = 54
    # Reserved 55-63

    # Administrative registers (64-79)
    ADMIN_DIRECTORY = 64
    ADMIN_EXTRA_CONTEXT = 65
    ADMIN_DOWNLOAD_STREAM = 66
    ADMIN_UPLOAD_STREAM = 67
    ADMIN_PASSWORD = 68
    ADMIN_COMMAND = 69
    HEARTBEAT = 70
    SHUTDOWN_REQUEST = 71
    # Reserved 72-79

    # Virtual registers - RX8025T RTC (80-95)
    RTC_SECOND = 80
    RTC_MINUTE = 81
    RTC_HOUR = 82
    RTC_WEEKDAY = 83
    RTC_DATE = 84
    RTC_MONTH = 85
    RTC_YEAR = 86
    RTC_RAM = 87
    RTC_MINUTE_ALARM = 88
    RTC_HOUR_ALARM = 89
    RTC_DAY_ALARM = 90
    RTC_TIMER_COUNTER_0 = 91
    RTC_TIMER_COUNTER_1 = 92
    RTC_EXTENSION = 93
    RTC_FLAG = 94
    RTC_CONTROL = 95

    # Virtual registers - TMP112 temperature sensor (96-103)
    TEMP_MSB = 96
    TEMP_LSB = 97
    TEMP_CONFIG_MSB = 98
    TEMP_CONFIG_LSB = 99
    TEMP_LOW_THRESHOLD_MSB = 100
    TEMP_LOW_THRESHOLD_LSB = 101
    TEMP_HIGH_THRESHOLD_MSB = 102
    TEMP_HIGH_THRESHOLD_LSB = 103
